config/routes.rb
Rails.application.routes.draw do

  #resources :charges

  resources :charges, only: [:new, :create]
  devise_for :users



  get 'orders/index'

  get 'customer', to: 'customer#new', as: 'sign_up'
  post 'customers', to: 'customer#create'
  get 'customer/index', to: 'customer#index', as: 'login_page'
  post 'customer/login', to: 'customer#login', as: 'login'
  get 'customer/logout', to: 'customer#destroy', as: 'logout'

  get 'checkout/index', to: 'checkout#index', as: 'checkout_page'
  get 'checkout/invoice', to: 'checkout#invoice', as: 'invoice'

  get 'cart', to: 'cart#show', as: 'cart'
  resources :product_orders, only: [:create, :update, :destroy]

  root 'products#main', as: 'main_page'

  get 'products', to: 'products#index', as: 'index_page'
  get 'products/:id', to: 'products#show', as: 'product'
  get 'search', to: 'search#index', as: 'product_search'

  get 'categories/:id', to: 'categories#show', as: 'category_page'

  get 'orders/new', to: 'orders#new', as: 'new_order'
  post 'orders/create', to: 'orders#create'

  get 'about', to: 'abouts#show', as: 'about_page'
  get 'contact', to: 'contact#new', as: 'contact_page'
  post 'contacts', to: 'contact#create'
  get 'thankyou', to: 'contact#thankyou', as: 'thankyou_page'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  validates :title, presence: true
  validates :tagline, presence: true
  validates :description, presence: true
  validates :image, presence: true

  mount_uploader :image, AboutUploader
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  validates :comment, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  belongs_to :province, optional: true

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true
  validates :phone, presence: true
  validates :phone, numericality: { only_integer: true }
  validates :address, presence: true
  validates :city, presence: true
  #validates :province, presence: true
  validates :postalcode, presence: true

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :product_orders
  belongs_to :customer, optional: true
  belongs_to :province, optional: true
  before_validation :set_customer_id
  before_validation :set_default_province
  before_validation :set_order_status
  before_validation :set_order_date

  validates :date, presence: true
  validates :status, presence: true
  #validates :gst, presence: true
  validates :gst, numericality: { only_float: true }, allow_blank: true
  #validates :pst, presence: true
  validates :pst, numericality: { only_float: true }, allow_blank: true
  #validates :customer_id, presence: true
  validates :customer_id, numericality: { only_integer: true }
  #validates :province_id, presence: true
  validates :province_id, numericality: { only_integer: true }

  private

  def set_order_status
    self.status = 'In Progress'
  end

  def set_order_date
    self.date = Time.now.strftime("%d/%m/%Y %H:%M")
  end

  def set_customer_id
    self.customer = Customer.find(1)
  end

  def set_default_province
    self.province = Province.find(1)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_orders
  belongs_to :category

  validates :sku, presence: true
  validates :name, presence: true
  validates :quantity, presence: true
  validates :quantity, numericality: { only_integer: true }
  validates :price, presence: true
  validates :price, numericality: { only_float: true }

  mount_uploader :image, ImageUploader

  def self.search search_term
    return scoped unless search_term.present?
    where(['name LIKE ? OR description LIKE ?', "%#{search_term}%", "%#{search_term}%"])
  end

  def self.category_search search_term, category_term
    return scoped unless search_term.present?
    where(['category_id = ? AND (name LIKE ? OR description LIKE ?)', "#{category_term}", "%#{search_term}%", "%#{search_term}%"])
  end
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
  before_save :set_prices

  #validates :product_id, presence: true
  #validates :order_id, presence: true
  #validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  def price
    if persisted?
      self[:price]
    else
      product.price
    end
  end

  def total_price
    price * quantity
  end

  private

  def set_prices
    self[:price] = price
    self[:total_price] = quantity * self[:price]
  end

end

app/models/province.rb
class Province < ApplicationRecord
  has_many :orders
  has_many :customers

  validates :code, presence: true
  validates :gst, presence: true
  validates :gst, numericality: { only_float: true }
  validates :pst, presence: true
  validates :pst, numericality: { only_float: true }

  #def display_name
   # code
  #end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :password, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.page(params[:page]).per(5)
  end

  def show
    @product = Product.find(params[:id])
    @product_order = current_order.product_orders.new
  end

  def category
    @products = Product.where(:category => params[:id])
  end

  def main
    @sale_products = Product.where(:sale => true)
    @new_products = Product.where(:new => true)
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/products/index.html.erb
<h1>Rebellion Fitness Gear Product Listing</h1>

<ul>
  <% @products.each do |product| %>
    <li>
      <% if product.image.present? %>
        <p><%= image_tag product.image.thumb.url %></p>
      <% end %>

      <%= link_to product.name, product_path(product) %></li>

  <% end %>
</ul>

<%= paginate @products %>

app/views/products/main.html.erb
<h2>On Sale</h2>

<ul>
  <% @sale_products.each do |product| %>
    <li>
      <% if product.image.present? %>
        <p><%= image_tag product.image.thumb.url %></p>
      <% end %>

      <%= link_to product.name, product_path(product) %></li>
    <li><strike>$<%= product.price %></strike> <b>$<%= product.sale_price %></b> </li>

  <% end %>
</ul>

<h2>New Products</h2>

<ul>
  <% @new_products.each do |product| %>
    <li>
      <% if product.image.present? %>
        <p><%= image_tag product.image.thumb.url %></p>
      <% end %>

      <%= link_to product.name, product_path(product) %></li>

  <% end %>
</ul>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<% if @product.sale %>
  <h2><strike>$<%= @product.price %></strike> <b>$<%= @product.sale_price %></b></h2>
<% else %>
  <h2>$<%= @product.price %></strike></h2>
<% end %>

<p><%= @product.description %></p>

<% if @product.image.present? %>
  <p><%= image_tag @product.image.product_view.url %></p>
<% end %>

<%= form_for @product_order, remote: true do |f| %>
  <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
  <%= f.hidden_field :product_id, value: @product.id.to_i %>
  <%= f.submit "Add to Cart", class: "btn btn-primary" %>
<% end %>


<h2>Specifications:</h2>

<ul>
  <% if @product.size.present? %>
    <li>Size: <%= @product.size %></li>
  <% end %>
  <% if @product.width.present? %>
    <li>Width: <%= @product.width %></li>
  <% end %>
  <% if @product.length.present? %>
    <li>Length: <%= @product.length %></li>
  <% end %>
  <% if @product.height.present? %>
    <li>Height: <%= @product.height %></li>
  <% end %>
  <% if @product.diameter.present? %>
    <li>Diameter: <%= @product.diameter %></li>
  <% end %>
  <% if @product.volume.present? %>
    <li>Volume: <%= @product.volume %></li>
  <% end %>
  <% if @product.weight.present? %>
    <li>Weight: <%= @product.weight %></li>
  <% end %>
  <% if @product.colour.present? %>
    <li>Colour: <%= @product.colour %></li>
  <% end %>
  <% if @product.material.present? %>
    <li>Material: <%= @product.material %></li>
  <% end %>
  <% if @product.finish.present? %>
    <li>Finish: <%= @product.finish %></li>
  <% end %>
  <% if @product.resistance.present? %>
    <li>Resistance Level: <%= @product.resistance %></li>
  <% end %>
  <% if @product.max_weight.present? %>
    <li>Maximum Supported Weight: <%= @product.max_weight %></li>
  <% end %>
</ul>





<p><%= link_to 'Go back to main page', main_page_path %></p>